name: Merge Schedule
on:
  pull_request:
    types:
      - opened
      - edited
  schedule:
    - cron: '24 19 * * *'
jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v1.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
